language: python
before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh
  - bash ~/miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda update -y conda
  - conda create -y -n pytorch-crf python=3.6
  - source activate pytorch-crf
  - conda install -y -c pytorch pytorch=1.0.0
  - export LD_LIBRARY_PATH="$HOME/miniconda/envs/pytorch-crf/lib:$LD_LIBRARY_PATH"
install:
  - pip install --ignore-installed -r requirements.txt
  - pip install .
script: pytest --cov
after_success: coveralls
